### ISSUE TITLE
"stack smashing" segmentation fault (?)

### ISSUE THREAD

**Issue by aphirst** [CyberShadow/znc-clientbuffer#1]
Originally reported: https://github.com/znc/znc/issues/1459

In the upstream report, I detail how both znc-git and znc-stable (1.6.5) suffer from a seemingly random segmentation fault issue. I'm now inclined to suspect not necessarily just znc, but also this add-on (it's the only one I use which isn't part of the main project).

In the coming hours I'll rebuild znc-clientbuffer with debug symbols, but perhaps until then some of the information in my upstream report may be of assistance.

I'll add more information to this thread as I get it.

**Comment by CyberShadow** [comment]
There is just one place in the ClientBuffer code where static arrays are used, and their use looks safe there, so there is no obvious part of the code which could cause a buffer overrun. (It might still be possible as a result of some variable lifetime bug though.)

In any case, this report is unactionable and not useful without additional information, such as a stack trace.

**Comment by aphirst** [comment]
Yeah. There are still some factors to exclude on my end, too. For example, I'll disable the plugin and study what impact that has. If the bug becomes nonreproducible, I'll close the issue here, and focus on the upstream report.

My current apparent finding is that the same setup works fine on an rPi2 (ALARM) but not on the ODROID-XU4, but I'd noticed they aren't on the same kernel version, so I'm letting znc run again on the Pi to see whether it conks out overnight.

**Comment by aphirst** [comment]
Having tested this again without znc-clientbuffer even installed, on both machines with the "stable" znc build from the ALARM repo, I get the same "stack smashing" segfault. So I can say with confidence that the clientbuffer add-on is *not* related.

Sorry for the radio noise.
