### ISSUE TITLE
autoadd shouldn't add a client if its identifier is not set

### ISSUE THREAD

**Issue by AntiCompositeNumber** [CyberShadow/znc-clientbuffer#12]
I had forgotten to pre-set an identifier for one of my clients, and connected with autoadd set in clientbuffer. This caused the client to be added to the client list with an empty identifier. Once I realized my mistake and set an identifier, I couldn't remove the client with the empty identifier from the client list.
```
<AntiComposite> ListClients
(*clientbuffer) +-------------+-----------+-----------+
(*clientbuffer) | Client      | TimeLimit | Connected |
(*clientbuffer) +-------------+-----------+-----------+
(*clientbuffer) |             |           | false     |
(*clientbuffer) +-------------+-----------+-----------+
```
It would be better to fail loudly here, so the user can set an identifier on the relevant client.

**Comment by CyberShadow** [comment]
Thanks!
