### ISSUE TITLE
clientbuffer doesn't build on znc 1.8.2

### ISSUE THREAD

**Issue by X73RN4L** [CyberShadow/znc-clientbuffer#14]
[username@server ~/.znc/modules/znc-clientbuffer]$ znc-buildmod clientbuffer.cpp
ld-elf.so.1: /usr/local/lib/libpython3.9.so.1.0: Undefined symbol "close_range@FBSD_1.6"
Traceback (most recent call last):
  File "/usr/local/bin/znc-buildmod", line 88, in <module>
    subprocess.check_call(command, cwd=build)
  File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/tmp/tmptta4bnfh']' returned non-zero exit status 1.

[username@server ~/.znc/modules/znc-clientbuffer]$ znc-buildmod clientbuffer.cpp
ld-elf.so.1: /usr/local/lib/libpython3.9.so.1.0: Undefined symbol "close_range@FBSD_1.6"
Traceback (most recent call last):
  File "/usr/local/bin/znc-buildmod", line 88, in <module>
    subprocess.check_call(command, cwd=build)
  File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/tmp/tmp5jacsd1o']' returned non-zero exit status 1.

[username@server ~/.znc/modules/znc-clientbuffer]$ znc-buildmod clientbuffer.cpp
ld-elf.so.1: /usr/local/lib/libpython3.9.so.1.0: Undefined symbol "close_range@FBSD_1.6"
Traceback (most recent call last):
  File "/usr/local/bin/znc-buildmod", line 88, in <module>
    subprocess.check_call(command, cwd=build)
  File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/tmp/tmpf1ggmlym']' returned non-zero exit status 1.

[username@server ~/.znc/modules/znc-clientbuffer]$ 

steps leading to this:
mkdir ~/.znc/modules ; cd ~/.znc/modules
wget https://github.com/CyberShadow/znc-clientbuffer/raw/master/clientbuffer.cpp
mkdir znc-clientbuffer
mv clientbuffer.cpp znc-clientbuffer
cd znc-clientbuffer
znc-buildmod clientbuffer.cpp

**Comment by CyberShadow** [comment]
I'm sorry, but this does not look like a problem with this module. It looks like there is something wrong with your Python installation.

Please seek support via the usual FreeBSD or ZNC support channels.
