### ISSUE TITLE
Seems to be replaying the entire buffer on ZNC 1.6.6

### ISSUE THREAD

**Issue by bhtooefr** [CyberShadow/znc-clientbuffer#2]
I've recently upgraded to ZNC 1.6.6 (from FreeBSD 10.4's pkg repos), and having switched to this fork of clientbuffer from the old version, I noticed that everything replays for every client - it doesn't seem to actually be managing the buffer (as in, it behaves like clientbuffer isn't even running), which kinda defeats the purpose. clientbuffer is clearly running - it can be queried, ListClients is accurate, etc., etc.

I'm suspecting a change in ZNC 1.6.6 caused this, as I tried using the old clientbuffer, and it fails in the same way in 1.6.6 as well.

**Comment by CyberShadow** [comment]
Is the client added (has `AddClient` been run / do you see anything in `ListClients` in a query to `*ClientBuffer`)?

**Comment by bhtooefr** [comment]
Yes, the clients are added, and `ListClients` returns the following:

```
[07:05] <bhtooefr> ListClients
[07:05] <*clientbuffer> +===============+===========+
[07:05] <*clientbuffer> | Client        | Connected |
[07:05] <*clientbuffer> +===============+===========+
[07:05] <*clientbuffer> | Android       | true      |
[07:05] <*clientbuffer> +---------------+-----------+
[07:05] <*clientbuffer> | hippasus      | false     |
[07:05] <*clientbuffer> +---------------+-----------+
[07:05] <*clientbuffer> | minenwerfer   | true      |
[07:05] <*clientbuffer> +---------------+-----------+
[07:05] <*clientbuffer> | uncannyvalley | true      |
[07:05] <*clientbuffer> +===============+===========+
```

(minenwerfer and Android are the machines I'm noticing this on, minenwerfer is running mIRC 7.51, Android is running latest AndChat. uncannyvalley just never disconnects (it's actually the machine that znc is running on), so I haven't had a reason to notice it there.)

**Comment by CyberShadow** [comment]
Can you check if the registry file (.znc/users/.../networks/.../moddata/clientbuffer/.registry) is being updated when a client receives a line?

**Comment by bhtooefr** [comment]
Looks like it is not being updated.

**Comment by CyberShadow** [comment]
Do you think you could roll back either ZNC or ClientBuffer to the version that previously worked, so that we can find out whether it was a change in ZNC or ClientBuffer that caused your setup to stop working?

**Comment by BtbN** [comment]
I'm using this on latest git master of znc and I have no issues at all.

**Comment by bhtooefr** [comment]
OK, that's weird.

Downgraded ZNC, it started working, reinstalled the newer version, it kept working.

¯\\_(ツ)_/¯

**Comment by CyberShadow** [comment]
Good to know you got it to work. If it happens again, you could try making a backup of the `.znc` directory before swapping versions - perhaps something there could be responsible for this hidden state leading towards it working / not working.
