### ISSUE TITLE
Unable to build on Archlinux ARM

### ISSUE THREAD

**Issue by aphirst** [CyberShadow/znc-clientbuffer#3]
Build log: https://ptpb.pw/xqcz

```
==> Starting build()...
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_C_COMPILER:

    /usr/lib/distcc/bin/cc

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_CXX_COMPILER:

    /usr/lib/distcc/bin/c++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
```

cmake seems to be trying to use distcc, despite the fact that on my machine this isn't installed, and that I have !distcc in my makepkg.conf.

I asked on Freenode #archlinux-arm and "rcf" suggested that the issue is actually with znc-buildmod, but I'd nonetheless prefer to not skip steps in escalating the issue to where it ultimately needs to be resolved.

In the meantime, if there's any other information I could provide which might be helpful, please just ask.

**Comment by CyberShadow** [comment]
Sorry, no idea, and there is definitely no code in this repository responsible for this issue.

Here is the entirety of [our Makefile](https://github.com/CyberShadow/znc-clientbuffer/blob/master/Makefile):

```make
clientbuffer.so : clientbuffer.cpp
	znc-buildmod clientbuffer.cpp

install: clientbuffer.so
	install clientbuffer.so /usr/lib/znc/
```

If I had to guess, maybe check `env | grep distcc` to see if you have any stray entries there.

**Comment by aphirst** [comment]
`env | grep distcc` gives no output, other than the usual newline.

In that case, do you reckon the right thing to do is to report this upstream to znc? If so, I'll make an issue there and refer back to this one.

**Comment by CyberShadow** [comment]
Yes, I think I'd do that if I did everything I could think of to rule out an issue with the environment.

Perhaps check if ZNC is buildable from source (either directly or via `makepkg`), if that's broken too, then it's one less dependency for the bug report.

**Comment by aphirst** [comment]
Yep, I am unable to build it via makepkg, or directly - I get the same errors. I'll mention that too upstream.

**Comment by aphirst** [comment]
Can confirm that this issue is indeed upstream.
