### ISSUE TITLE
.registry file getting crazy large, causing high cpu usage

### ISSUE THREAD

**Issue by ItsOnlyBinary** [CyberShadow/znc-clientbuffer#4]
Ive been having some issues with high cpu usage from znc. Seems to be caused by this module.

I'm on freenode with 17 channels and two devices (clients) but my .registry file is 45,000 lines long

seems to be creating an entry for every user its ever seen

znc 1.7.1

**Comment by CyberShadow** [comment]
The creation of spurious registry entries should now be fixed.

However, the high CPU usage is likely not related. As far as I've observed, the entries are created gradually, when IRC users disconnect while in a channel you're also in (but possibly in other circumstances too). Another point is that I've observed the same issue on my system (the Freenode registry file had cca 65000 entries), and I'm not observing high CPU usage from ZNC.

Please try using a profiler (or, attaching gdb a few times and looking at the backtrace) to find the real source of the high CPU usage.

**Comment by ItsOnlyBinary** [comment]
The high cpu was likely due to server being intel atom n2800 + mechanical harddrive.

does seem to have returned to normal since i deleted the .registry file and restarted.

testing new module now, thanks greatly for sorting this out so promptly
